In [1]:
import numpy as np

In [12]:
a = np.array([1,2,3],dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [49]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#Get Dimension
a.ndim

1

In [8]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get Type
b.dtype

dtype('float64')

In [13]:
# Get Size
a.itemsize

4

In [15]:
#  Get totsl size
a.nbytes

12

##### Accessing/Changing specific elements, rows, columns,etc

In [51]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
#  Get a specific element[r,c]
a[1,5]

13

In [19]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [21]:
# Getting a little more fancy [startindex: endindex: stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [25]:
a[0, 1:-1:2]

array([2, 4, 6])

In [30]:
a[:,2]=[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 13, 14]])

In [53]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [54]:
#  Get specific element (work outside in)
b[0,1,1]

4

In [56]:
b[:,1,:] = [[9,9],[8,8]]

In [57]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#####  Initializing Different Types of Arrays

In [59]:
# All 0s  matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [62]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [67]:
# Any other number(full_like)
np.full_like(a.shape,4)

array([4, 4])

In [72]:
#  Random decimal numbers
np.random.rand(4,2)

array([[0.23526931, 0.24009288],
       [0.81233751, 0.05851088],
       [0.01460624, 0.1991116 ],
       [0.37945472, 0.58366693]])

In [71]:
np.random.random_sample(a.shape)

array([[0.29136089, 0.18619992, 0.8744692 , 0.19168509, 0.36870481,
        0.93198207, 0.83594126],
       [0.27667535, 0.60304927, 0.06704108, 0.51219723, 0.82274752,
        0.48543824, 0.82263014]])

In [75]:
# Random Integer values
np.random.randint(5, 10,size=(3,3))

array([[5, 9, 9],
       [8, 8, 7],
       [5, 5, 6]])

In [77]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
# Repeat an array 
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [91]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be  careful when copying array

In [97]:
a =  np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


##### Mathematics

In [99]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [100]:
a+2

array([3, 4, 5, 6])

In [103]:
b = np.array([1,2,3,4])

In [104]:
a+b

array([2, 4, 6, 8])

In [105]:
a**2

array([ 1,  4,  9, 16])

In [106]:
#  Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [118]:
a = np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [112]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,1],[3,4,3]])

In [121]:
print(a)
print(b)
np.matmul(a,b)

[[1, 0], [0, 1]]
[[4, 1], [2, 2]]


array([[4, 1],
       [2, 2]])

In [120]:
a = [[1, 0], [0, 1]]
print(a)
print(b)
b = [[4, 1], [2, 2]]
np.matmul(a, b)

[[1, 0], [0, 1]]
[[4, 1], [2, 2]]


array([[4, 1],
       [2, 2]])

In [123]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [124]:
stats =  np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
np.min(stats,axis=1)

array([1, 4])

In [126]:
np.max(stats)

6

In [130]:
np.sum(stats,axis=0)

array([5, 7, 9])

##### Reorganizing Arrays

In [133]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [135]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [138]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##### Miscellaneous

###### Load Data from File

In [144]:
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

###### Boolean Masking and Advanced Indexing

In [147]:
filedata[filedata >= 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [148]:
## You can index with a list in Numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [149]:
np.any(filedata > 50,  axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [150]:
np.all(filedata > 50,  axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [152]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [162]:
a = np.arange(1,31,1).reshape((6,5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [166]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [167]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [169]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])